phases:
- template: /eng/build.yml
  parameters:
    name: Windows
    agentOs: Windows_NT
    queue: 
      name: Hosted VS2017
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: CentOS_7
    agentOs: Linux
    dockerImage: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-3e800f1-20190501005343
    queue:
      name: Hosted Ubuntu 1604
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

- template: /eng/build.yml
  parameters:
    name: MacOS
    agentOs: Darwin
    queue: 
      name: Hosted macOS
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _BuildArch: x64
        Build_Release:
          _BuildConfig: Release
          _BuildArch: x64

